/**
 * Generate the Prism operator keypair.
 *
 * ECDSA, not ED25519: @x402/hedera's live path and every Hedera x402 facilitator
 * assume ECDSA keys for client and fee payer.
 *
 * No account exists yet. Hedera auto-creates one the first time value lands on the
 * key's EVM address, so the address below is what gets funded, and the 0.0.x id is
 * assigned by the network at that moment. `npm run whoami` resolves it afterwards.
 */
import { writeFileSync, existsSync, readFileSync } from "node:fs";
import { PrivateKey } from "@hiero-ledger/sdk";

const ENV_PATH = new URL("../.env", import.meta.url);

if (existsSync(ENV_PATH) && readFileSync(ENV_PATH, "utf8").includes("OPERATOR_KEY=")) {
  console.error("Refusing to overwrite: .env already holds an OPERATOR_KEY.");
  console.error("Delete it by hand first if you really want a fresh operator.");
  process.exit(1);
}

const key = PrivateKey.generateECDSA();
const evmAddress = `0x${key.publicKey.toEvmAddress()}`;

writeFileSync(
  ENV_PATH,
  [
    "# Prism operator — Hedera testnet. ECDSA. Generated by scripts/keygen.mjs.",
    "# Gitignored. Testnet only; never reuse this key on mainnet.",
    `OPERATOR_KEY=${key.toStringRaw()}`,
    `OPERATOR_EVM_ADDRESS=${evmAddress}`,
    "OPERATOR_ID=",
    "HEDERA_NETWORK=testnet",
    "MIRROR_NODE_URL=https://testnet.mirrornode.hedera.com",
    "USDC_TOKEN_ID=0.0.429274",
    "",
  ].join("\n"),
);

console.log("Operator keypair written to .env (gitignored).\n");
console.log(`  EVM address : ${evmAddress}`);
console.log(`  Public key  : ${key.publicKey.toStringRaw()}`);
console.log(`  Private key : ${key.toStringRaw().slice(0, 8)}… (full value in .env)`);
console.log(`\nAccount id    : not assigned yet — funding this address creates it.`);
